server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/smart_community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3s
